### ISSUE TITLE
openapi3 스펙 구현

### ISSUE THREAD

**Issue by raeperd** [OPGG-HACKTHON/gameflix#1]
# Motivation
openapi3 스펙을 먼저 구현하고, 프론트엔드와 백엔드가 동시에 개발 될 수 있도록 지원 

# TODO 
- [x] openapi3.json 구현 
- [x] github page 로 배포 
- [ ] [About – IGDB API docs](https://api-docs.igdb.com/#about) 참고해서 수정

# Reference 
[swagger | OpenAPI Specification](https://swagger.io/specification/)
[springdoc | what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml)

**Comment by raeperd** [comment]
- [ ] [About – IGDB API docs](https://api-docs.igdb.com/#about) 참고해서 수정

**Comment by raeperd** [comment]
[7/27 회의록](https://www.notion.so/07-27-d67c379e6e394c2cb8a959a4c9109030)

### 필수 구현 기능
1. Google 로그인
2. 내가 구매한 / 플레이 중인 게임 목록
    1. Steam
    2. EPIC games
    3. blizzard
3. 수동으로 새 게임 추가
4. 게임에 대한 상세 정보

### 추가적인 기능
1. 장르별로 게임 가져오기 
2. 사용자별 추천 기능
3. 뉴비 추천(인기순)
4. 게임 평가
5. 최근 인기 게임 목록

**Comment by raeperd** [comment]
[Game – IGDB API docs](https://api-docs.igdb.com/#game)

### 포함할 필드 
- rating
- rating_count
- cover
- create_at
- genres
- name
- platforms
- slug
- updated_at
- url

### 애매함 
- screenshots 
- status
- tags
- videos
- websites
