### ISSUE TITLE
swagger try out 기능이 동작하도록 구현

### ISSUE THREAD

**Issue by raeperd** [OPGG-HACKTHON/gameflix#36]
# TODO
- [ ] CORS 설정 반영
- [ ] API 수정사항 새로 반영 by #19 
- [ ] AWS Load Balancer 의 주소 추가 by #32 

# Description
- #32 이후 swagger 에서 응답을 받기 위해서는 cors 설정이 되어 있어야함
- #30 기능 구현 이전에 #19 이슈의 변경사항을 먼저 문서에 반영할 필요가 있음
